### ISSUE TITLE
[BUG] Plug-In fails to initalize under macos/rhino8

### ISSUE THREAD

**Issue by anhelmphono** [design-to-production/D2P-Components#2]
**Describe the bug**
Plug-In keeps failing to initialize under MacOS / Rhino 8 after successful installation via package-manager. Following Error-Message appears in the console:

Command: Grasshopper
An error occured during GHA assembly loading:
  Path: /Users/digitalcrafter/Library/Application Support/McNeel/Rhinoceros/packages/8.0/d2p-components/1.0.0-beta/D2P_GrasshopperTools.gha
  Exception System.IO.FileLoadException: 
  Message: Could not load file or assembly 'D2P_GrasshopperTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**To Reproduce**
1. Open new Document
2. Initial Start-Up Grasshopper with "Grasshopper" Command

**Expected behavior**
Seeing a new Panel with various Icons for the GH-Components of the d2p-component plugin

**Screenshots**

**Rhino System Information:**
Rhino 8 SR11 2024-9-10 (Rhino 8, 8.11.24254.15002, Git hash:master @ d3c11108eae09fadc146928ba51b9b182a05303f)
License type: Educational, build 2024-09-10
License details: Stand-Alone

Apple macOS Version 14.4.1 (Build 23E224) (Physical RAM: 36GB)
Mac Model Identifier: Mac15,6
Language: en
.NET 7.0.0

Metal GPU Family Apple 7
Metal GPU Family Common 3
Metal GPU Family Mac 2
Graphics processors
  Apple M3 Pro
    Color LCD (1512 x 982 @ 120.00Hz)
    DELL U2723QE (1920 x 1080 @ 60.00Hz)
GPU Vendor: Apple

USB devices
  Realtek: USB 10/100/1000 LAN
  Realtek: USB2.0 HID
  Generic: 4-Port USB 2.0 Hub

Bluetooth devices
  None

Third party kernel extensions
  None

Third party plugins
  /usr/lib/swift/libswiftCore.dylib
  /usr/lib/swift/libswiftCoreFoundation.dylib
  /usr/lib/swift/libswiftCoreGraphics.dylib
  /usr/lib/swift/libswiftCoreImage.dylib
  /usr/lib/swift/libswiftDarwin.dylib
  /usr/lib/swift/libswiftDispatch.dylib
  /usr/lib/swift/libswiftIOKit.dylib
  /usr/lib/swift/libswiftMetal.dylib
  /usr/lib/swift/libswiftOSLog.dylib
  /usr/lib/swift/libswiftObjectiveC.dylib
  /usr/lib/swift/libswiftQuartzCore.dylib
  /usr/lib/swift/libswiftUniformTypeIdentifiers.dylib
  /usr/lib/swift/libswiftXPC.dylib
  /usr/lib/swift/libswift_Concurrency.dylib
  /usr/lib/swift/libswiftos.dylib
  /usr/lib/swift/libswiftsimd.dylib
  /usr/lib/swift/libswift_StringProcessing.dylib
  /usr/lib/swift/libswift_RegexParser.dylib
  /usr/lib/swift/libswiftCryptoTokenKit.dylib
  /usr/lib/usd/libusd_ms.dylib
  /usr/lib/swift/libswiftCoreAudio.dylib
  /usr/lib/swift/libswiftCoreLocation.dylib
  /usr/lib/swift/libswiftCoreMedia.dylib
  /usr/lib/swift/libswiftCompression.dylib
  /usr/lib/swift/libswiftCoreMIDI.dylib
  /usr/lib/swift/libswiftAVFoundation.dylib
  /usr/lib/swift/libswiftCoreML.dylib
  /usr/lib/swift/libswiftFileProvider.dylib
  /usr/lib/swift/libswiftIntents.dylib
  /usr/lib/swift/libswiftAccelerate.dylib
  /usr/lib/swift/libswiftGLKit.dylib
  /usr/lib/swift/libswiftGameplayKit.dylib
  /usr/lib/swift/libswiftMetalKit.dylib
  /usr/lib/swift/libswiftModelIO.dylib
  /usr/lib/swift/libswiftSceneKit.dylib
  /usr/lib/swift/libswiftSpriteKit.dylib
  /usr/lib/swift/libswiftVision.dylib
  /usr/lib/swift/libswiftRegexBuilder.dylib
  /usr/lib/swift/libswiftDemangle.dylib
  /usr/lib/swift/libswiftShazamKit.dylib
  /usr/lib/swift/libswiftObservation.dylib
  /usr/lib/swift/libswiftVideoToolbox.dylib
  /usr/lib/swift/libswiftWebKit.dylib
  /usr/lib/swift/libswiftNaturalLanguage.dylib
  /usr/lib/swift/libswiftSystem.dylib
  /usr/lib/swift/libswiftMapKit.dylib
  /usr/lib/log/liblog_network.dylib

Rhino plugins that do not ship with Rhino
  /Users/digitalcrafter/Library/Application Support/McNeel/Rhinoceros/8.0/MacPlugIns/Enscape.Rhino8.Plugin.rhp	"Enscape.Rhino8.Plugin"	4.1.0.2288

Rhino plugins that ship with Rhino
  /Applications/Rhino 8.app/Contents/Frameworks/RhMaterialEditor.framework	"Renderer Development Kit"	8.11.24254.1002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/Commands.rhp	"Commands"	8.11.24254.15002
  /Applications/Rhino 8.app/Contents/PlugIns/NamedSnapshots.rhp	"Snapshots"	8.11.24254.1002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/RDK_EtoUI.rhp	"RDK_EtoUI"	8.11.24254.15002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/MeshCommands.rhp	"MeshCommands"	8.11.24254.15002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/RhinoRenderCycles.rhp	"Rhino Render"	8.11.24254.15002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/RhinoCycles.rhp	"RhinoCycles"	8.11.24254.15002
  /Applications/Rhino 8.app/Contents/PlugIns/SectionTools.rhp	"SectionTools"	8.11.24254.1002
  /Applications/Rhino 8.app/Contents/PlugIns/Displacement.rhp	"Displacement"	8.11.24254.1002
  /Applications/Rhino 8.app/Contents/PlugIns/PanelingTools.rhp	"PanelingTools"	8.11.24254.1002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/RhinoDLR_Python.rhp	"IronPython"	8.11.24254.15002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/GrasshopperPlugin.rhp	"Grasshopper"	8.11.24254.15002
  /Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Resources/ManagedPlugIns/RhinoCodePlugin.rhp	"RhinoCodePlugin"	8.11.24254.15002

**Additional context**
Add any other context about the problem here. If the issue is related to geometry or any other user specific data attach a minimal grasshopper definition to this bug report.
<img width="912" alt="Bildschirmfoto 2024-09-19 um 17 23 45" src="https://github.com/user-attachments/assets/4f8e7171-4c7f-46d9-8d62-1fc853ead6fb">

**Comment by bastiannispel** [comment]
Hello @anhelmphono,

thanks for your feedback it's appreciated !
The supported target platforms for the beta release have been setup incorrectly.
I created a feature request for that issue which has the highest priority for the v1.0.0 release as of now (see #8)
Sorry for the inconveniences !
